from collections.abc import Mapping
from typing import Any

class Program:
    @property
    def qualified_name(self) -> str: ...
    def signature_json(self) -> str: ...
    def ir_json(self) -> str: ...
    def compilation_certificate_json(self) -> str | None: ...
    def validation_certificate_json(self) -> str: ...
    def history_json(self) -> str: ...
    def source_partition_json(self) -> str: ...
    def evaluate(self, inputs: Mapping[str, float]) -> tuple[list[float], str]: ...
    def value_and_gradient(
        self, inputs: Mapping[str, float]
    ) -> tuple[list[float], list[dict[str, float]], str]: ...

class Workspace:
    def module_names(self) -> list[str]: ...
    def function(self, module: str, function: str) -> Program: ...

def compile_module(source: str) -> Workspace: ...
def link_modules(sources: list[str]) -> Workspace: ...
def load_program_json(source: str) -> Program: ...
