from collections.abc import Mapping
from typing import Any

class Program:
    @property
    def qualified_name(self) -> str: ...
    def signature_json(self) -> str: ...
    def ir_json(self) -> str: ...
    def compilation_certificate_json(self) -> str | None: ...
    def validation_certificate_json(self) -> str: ...
    def history_json(self) -> str: ...
    def source_partition_json(self) -> str: ...
    def graft_trace(self) -> tuple[str, str] | None: ...
    def causal_cut(self, completed: list[int]) -> tuple[str, str]: ...
    def advance_causal_cut(
        self, completed: list[int], event: int
    ) -> tuple[str, str]: ...
    def program_slice(
        self, lower_completed: list[int], upper_completed: list[int]
    ) -> tuple[str, str]: ...
    def compose_program_slices(
        self,
        lower_completed: list[int],
        middle_completed: list[int],
        upper_completed: list[int],
    ) -> tuple[str, str]: ...
    def triadic_observer_transition_v0(
        self,
        input_domains: list[str],
        lower_completed: list[int],
        upper_completed: list[int],
    ) -> tuple[str, str]: ...
    def compose_triadic_observer_transitions_v0(
        self,
        input_domains: list[str],
        lower_completed: list[int],
        middle_completed: list[int],
        upper_completed: list[int],
    ) -> tuple[str, str]: ...
    def evaluate(self, inputs: Mapping[str, float]) -> tuple[list[float], str]: ...
    def value_and_gradient(
        self, inputs: Mapping[str, float]
    ) -> tuple[list[float], list[dict[str, float]], str]: ...

class Workspace:
    def module_names(self) -> list[str]: ...
    def function(self, module: str, function: str) -> Program: ...

def compile_module(source: str) -> Workspace: ...
def link_modules(sources: list[str]) -> Workspace: ...
def load_program_json(source: str) -> Program: ...
