$[ /home/ubuntu/MetaMath/set.mm/set.mm $]
adva152e0 $p |- ( A e. CC -> ( 2 x. ( 2 x. A ) ) = ( 2 x. ( A + A ) ) ) $= cA cc wcel c2 cA cmul co cA cA caddc co c2 cmul cA cc wcel cA cA cc wcel id 2timesd oveq2d $.
adva152e1 $p |- ( A e. CC -> ( 2 x. ( A + A ) ) = ( 2 x. ( 2 x. A ) ) ) $= cA cc wcel cA cA caddc co c2 cA cmul co c2 cmul cA cc wcel c2 cA cmul co cA cA caddc co cA cc wcel cA cA cc wcel id 2timesd eqcomd oveq2d $.
adva152e2 $p |- ( A e. CC -> ( 2 x. ( 2 x. A ) ) = ( 2 x. ( A + A ) ) ) $= cA cc wcel c2 cA cmul co cA cA caddc co c2 cmul cA cc wcel cA cA cc wcel id 2timesd oveq2d $.
adva152e3 $p |- ( A e. CC -> ( 2 x. ( A + A ) ) = ( 2 x. ( 2 x. A ) ) ) $= cA cc wcel cA cA caddc co c2 cA cmul co c2 cmul cA cc wcel c2 cA cmul co cA cA caddc co cA cc wcel cA cA cc wcel id 2timesd eqcomd oveq2d $.
adva152e4 $p |- ( A e. CC -> ( 2 x. ( 2 x. A ) ) = ( ( 2 x. A ) + ( 2 x. A ) ) ) $= cA cc wcel c2 cA cmul co cA cc wcel c2 cA cA cc wcel 2cnd cA cc wcel id mulcld 2timesd $.
adva152e5 $p |- ( A e. CC -> ( ( 2 x. A ) + ( 2 x. A ) ) = ( ( A + A ) + ( 2 x. A ) ) ) $= cA cc wcel c2 cA cmul co cA cA caddc co c2 cA cmul co caddc cA cc wcel cA cA cc wcel id 2timesd oveq1d $.
adva152e6 $p |- ( A e. CC -> ( ( A + A ) + ( 2 x. A ) ) = ( ( A + A ) + ( A + A ) ) ) $= cA cc wcel c2 cA cmul co cA cA caddc co cA cA caddc co caddc cA cc wcel cA cA cc wcel id 2timesd oveq2d $.
adva152e7 $p |- ( A e. CC -> ( 2 x. ( 2 x. A ) ) = ( 2 x. ( A + A ) ) ) $= cA cc wcel c2 cA cmul co cA cA caddc co c2 cmul cA cc wcel cA cA cc wcel id 2timesd oveq2d $.
adva152e8 $p |- ( A e. CC -> ( 2 x. ( A + A ) ) = ( ( A + A ) + ( A + A ) ) ) $= cA cc wcel cA cA caddc co cA cc wcel cA cA cA cc wcel id cA cc wcel id addcld 2timesd $.
adva152e9 $p |- ( A e. CC -> ( 2 x. ( 2 x. A ) ) = ( 2 x. ( A + A ) ) ) $= cA cc wcel c2 cA cmul co cA cA caddc co c2 cmul cA cc wcel cA cA cc wcel id 2timesd oveq2d $.
adva152e10 $p |- ( A e. CC -> ( 2 x. ( A + A ) ) = ( ( A + A ) + ( A + A ) ) ) $= cA cc wcel cA cA caddc co cA cc wcel cA cA cA cc wcel id cA cc wcel id addcld 2timesd $.
adva152e11 $p |- ( A e. CC -> ( 2 x. ( 2 x. A ) ) = ( ( 2 x. A ) + ( 2 x. A ) ) ) $= cA cc wcel c2 cA cmul co cA cc wcel c2 cA cA cc wcel 2cnd cA cc wcel id mulcld 2timesd $.
adva152e12 $p |- ( A e. CC -> ( ( 2 x. A ) + ( 2 x. A ) ) = ( ( 2 x. A ) + ( A + A ) ) ) $= cA cc wcel c2 cA cmul co cA cA caddc co c2 cA cmul co caddc cA cc wcel cA cA cc wcel id 2timesd oveq2d $.
adva152e13 $p |- ( A e. CC -> ( ( 2 x. A ) + ( A + A ) ) = ( ( A + A ) + ( A + A ) ) ) $= cA cc wcel c2 cA cmul co cA cA caddc co cA cA caddc co caddc cA cc wcel cA cA cc wcel id 2timesd oveq1d $.
adva152e14 $p |- ( A e. CC -> ( 2 x. ( 2 x. A ) ) = ( ( 2 x. A ) + ( 2 x. A ) ) ) $= cA cc wcel c2 cA cmul co cA cc wcel c2 cA cA cc wcel 2cnd cA cc wcel id mulcld 2timesd $.
adva152e15 $p |- ( A e. CC -> ( ( 2 x. A ) + ( 2 x. A ) ) = ( ( A + A ) + ( 2 x. A ) ) ) $= cA cc wcel c2 cA cmul co cA cA caddc co c2 cA cmul co caddc cA cc wcel cA cA cc wcel id 2timesd oveq1d $.
adva152e16 $p |- ( A e. CC -> ( ( A + A ) + ( 2 x. A ) ) = ( ( A + A ) + ( A + A ) ) ) $= cA cc wcel c2 cA cmul co cA cA caddc co cA cA caddc co caddc cA cc wcel cA cA cc wcel id 2timesd oveq2d $.
adva152e17 $p |- ( A e. CC -> ( 2 x. ( 2 x. A ) ) = ( ( 2 x. A ) + ( 2 x. A ) ) ) $= cA cc wcel c2 cA cmul co cA cc wcel c2 cA cA cc wcel 2cnd cA cc wcel id mulcld 2timesd $.
adva152e18 $p |- ( A e. CC -> ( ( 2 x. A ) + ( 2 x. A ) ) = ( ( A + A ) + ( 2 x. A ) ) ) $= cA cc wcel c2 cA cmul co cA cA caddc co c2 cA cmul co caddc cA cc wcel cA cA cc wcel id 2timesd oveq1d $.
adva152e19 $p |- ( A e. CC -> ( ( A + A ) + ( 2 x. A ) ) = ( ( A + A ) + ( A + A ) ) ) $= cA cc wcel c2 cA cmul co cA cA caddc co cA cA caddc co caddc cA cc wcel cA cA cc wcel id 2timesd oveq2d $.
adva152e20 $p |- ( A e. CC -> ( 2 x. ( 2 x. A ) ) = ( 2 x. ( A + A ) ) ) $= cA cc wcel c2 cA cmul co cA cA caddc co c2 cmul cA cc wcel cA cA cc wcel id 2timesd oveq2d $.
adva152e21 $p |- ( A e. CC -> ( 2 x. ( A + A ) ) = ( ( A + A ) + ( A + A ) ) ) $= cA cc wcel cA cA caddc co cA cc wcel cA cA cA cc wcel id cA cc wcel id addcld 2timesd $.
adva152e22 $p |- ( A e. CC -> ( 2 x. ( 2 x. A ) ) = ( 2 x. ( A + A ) ) ) $= cA cc wcel c2 cA cmul co cA cA caddc co c2 cmul cA cc wcel cA cA cc wcel id 2timesd oveq2d $.
adva152e23 $p |- ( A e. CC -> ( 2 x. ( A + A ) ) = ( ( A + A ) + ( A + A ) ) ) $= cA cc wcel cA cA caddc co cA cc wcel cA cA cA cc wcel id cA cc wcel id addcld 2timesd $.
adva152e24 $p |- ( A e. CC -> ( 2 x. ( 2 x. A ) ) = ( 2 x. ( A + A ) ) ) $= cA cc wcel c2 cA cmul co cA cA caddc co c2 cmul cA cc wcel cA cA cc wcel id 2timesd oveq2d $.
adva152e25 $p |- ( A e. CC -> ( 2 x. ( A + A ) ) = ( ( A + A ) + ( A + A ) ) ) $= cA cc wcel cA cA caddc co cA cc wcel cA cA cA cc wcel id cA cc wcel id addcld 2timesd $.
adva152e26 $p |- ( A e. CC -> ( ( A + A ) + ( A + A ) ) = ( ( 2 x. A ) + ( A + A ) ) ) $= cA cc wcel cA cA caddc co c2 cA cmul co cA cA caddc co caddc cA cc wcel c2 cA cmul co cA cA caddc co cA cc wcel cA cA cc wcel id 2timesd eqcomd oveq1d $.
adva152e27 $p |- ( A e. CC -> ( ( 2 x. A ) + ( A + A ) ) = ( ( 2 x. A ) + ( 2 x. A ) ) ) $= cA cc wcel cA cA caddc co c2 cA cmul co c2 cA cmul co caddc cA cc wcel c2 cA cmul co cA cA caddc co cA cc wcel cA cA cc wcel id 2timesd eqcomd oveq2d $.
adva152e28 $p |- ( A e. CC -> ( ( 2 x. A ) + ( 2 x. A ) ) = ( ( A + A ) + ( 2 x. A ) ) ) $= cA cc wcel c2 cA cmul co cA cA caddc co c2 cA cmul co caddc cA cc wcel cA cA cc wcel id 2timesd oveq1d $.
adva152e29 $p |- ( A e. CC -> ( ( A + A ) + ( 2 x. A ) ) = ( ( A + A ) + ( A + A ) ) ) $= cA cc wcel c2 cA cmul co cA cA caddc co cA cA caddc co caddc cA cc wcel cA cA cc wcel id 2timesd oveq2d $.
adva152e30 $p |- ( A e. CC -> ( ( A + A ) + ( A + A ) ) = ( ( A + A ) + ( 2 x. A ) ) ) $= cA cc wcel cA cA caddc co c2 cA cmul co cA cA caddc co caddc cA cc wcel c2 cA cmul co cA cA caddc co cA cc wcel cA cA cc wcel id 2timesd eqcomd oveq2d $.
adva152e31 $p |- ( A e. CC -> ( ( A + A ) + ( 2 x. A ) ) = ( ( A + A ) + ( A + A ) ) ) $= cA cc wcel c2 cA cmul co cA cA caddc co cA cA caddc co caddc cA cc wcel cA cA cc wcel id 2timesd oveq2d $.
adva152e32 $p |- ( A e. CC -> ( ( A + A ) + ( A + A ) ) = ( 2 x. ( A + A ) ) ) $= cA cc wcel c2 cA cA caddc co cmul co cA cA caddc co cA cA caddc co caddc co cA cc wcel cA cA caddc co cA cc wcel cA cA cA cc wcel id cA cc wcel id addcld 2timesd eqcomd $.
adva152e33 $p |- ( A e. CC -> ( 2 x. ( A + A ) ) = ( 2 x. ( 2 x. A ) ) ) $= cA cc wcel cA cA caddc co c2 cA cmul co c2 cmul cA cc wcel c2 cA cmul co cA cA caddc co cA cc wcel cA cA cc wcel id 2timesd eqcomd oveq2d $.
adva152e34 $p |- ( A e. CC -> ( ( A + A ) + ( A + A ) ) = ( ( 2 x. A ) + ( A + A ) ) ) $= cA cc wcel cA cA caddc co c2 cA cmul co cA cA caddc co caddc cA cc wcel c2 cA cmul co cA cA caddc co cA cc wcel cA cA cc wcel id 2timesd eqcomd oveq1d $.
adva152e35 $p |- ( A e. CC -> ( ( 2 x. A ) + ( A + A ) ) = ( ( 2 x. A ) + ( 2 x. A ) ) ) $= cA cc wcel cA cA caddc co c2 cA cmul co c2 cA cmul co caddc cA cc wcel c2 cA cmul co cA cA caddc co cA cc wcel cA cA cc wcel id 2timesd eqcomd oveq2d $.
adva152e36 $p |- ( A e. CC -> ( ( 2 x. A ) + ( 2 x. A ) ) = ( ( A + A ) + ( 2 x. A ) ) ) $= cA cc wcel c2 cA cmul co cA cA caddc co c2 cA cmul co caddc cA cc wcel cA cA cc wcel id 2timesd oveq1d $.
adva152e37 $p |- ( A e. CC -> ( ( A + A ) + ( 2 x. A ) ) = ( ( A + A ) + ( A + A ) ) ) $= cA cc wcel c2 cA cmul co cA cA caddc co cA cA caddc co caddc cA cc wcel cA cA cc wcel id 2timesd oveq2d $.
adva152e38 $p |- ( A e. CC -> ( ( A + A ) + ( A + A ) ) = ( 2 x. ( A + A ) ) ) $= cA cc wcel c2 cA cA caddc co cmul co cA cA caddc co cA cA caddc co caddc co cA cc wcel cA cA caddc co cA cc wcel cA cA cA cc wcel id cA cc wcel id addcld 2timesd eqcomd $.
adva152e39 $p |- ( A e. CC -> ( 2 x. ( A + A ) ) = ( 2 x. ( 2 x. A ) ) ) $= cA cc wcel cA cA caddc co c2 cA cmul co c2 cmul cA cc wcel c2 cA cmul co cA cA caddc co cA cc wcel cA cA cc wcel id 2timesd eqcomd oveq2d $.
adva152e40 $p |- ( A e. CC -> ( ( A + A ) + ( A + A ) ) = ( 2 x. ( A + A ) ) ) $= cA cc wcel c2 cA cA caddc co cmul co cA cA caddc co cA cA caddc co caddc co cA cc wcel cA cA caddc co cA cc wcel cA cA cA cc wcel id cA cc wcel id addcld 2timesd eqcomd $.
adva152e41 $p |- ( A e. CC -> ( 2 x. ( A + A ) ) = ( 2 x. ( 2 x. A ) ) ) $= cA cc wcel cA cA caddc co c2 cA cmul co c2 cmul cA cc wcel c2 cA cmul co cA cA caddc co cA cc wcel cA cA cc wcel id 2timesd eqcomd oveq2d $.
adva152e42 $p |- ( A e. CC -> ( ( A + A ) + ( A + A ) ) = ( ( 2 x. A ) + ( A + A ) ) ) $= cA cc wcel cA cA caddc co c2 cA cmul co cA cA caddc co caddc cA cc wcel c2 cA cmul co cA cA caddc co cA cc wcel cA cA cc wcel id 2timesd eqcomd oveq1d $.
adva152e43 $p |- ( A e. CC -> ( ( 2 x. A ) + ( A + A ) ) = ( ( A + A ) + ( A + A ) ) ) $= cA cc wcel c2 cA cmul co cA cA caddc co cA cA caddc co caddc cA cc wcel cA cA cc wcel id 2timesd oveq1d $.
adva152e44 $p |- ( A e. CC -> ( ( A + A ) + ( A + A ) ) = ( 2 x. ( A + A ) ) ) $= cA cc wcel c2 cA cA caddc co cmul co cA cA caddc co cA cA caddc co caddc co cA cc wcel cA cA caddc co cA cc wcel cA cA cA cc wcel id cA cc wcel id addcld 2timesd eqcomd $.
adva152e45 $p |- ( A e. CC -> ( 2 x. ( A + A ) ) = ( ( A + A ) + ( A + A ) ) ) $= cA cc wcel cA cA caddc co cA cc wcel cA cA cA cc wcel id cA cc wcel id addcld 2timesd $.
adva152e46 $p |- ( A e. CC -> ( ( A + A ) + ( A + A ) ) = ( ( A + A ) + ( 2 x. A ) ) ) $= cA cc wcel cA cA caddc co c2 cA cmul co cA cA caddc co caddc cA cc wcel c2 cA cmul co cA cA caddc co cA cc wcel cA cA cc wcel id 2timesd eqcomd oveq2d $.
adva152e47 $p |- ( A e. CC -> ( ( A + A ) + ( 2 x. A ) ) = ( ( 2 x. A ) + ( 2 x. A ) ) ) $= cA cc wcel cA cA caddc co c2 cA cmul co c2 cA cmul co caddc cA cc wcel c2 cA cmul co cA cA caddc co cA cc wcel cA cA cc wcel id 2timesd eqcomd oveq1d $.
adva152e48 $p |- ( A e. CC -> ( ( 2 x. A ) + ( 2 x. A ) ) = ( ( 2 x. A ) + ( A + A ) ) ) $= cA cc wcel c2 cA cmul co cA cA caddc co c2 cA cmul co caddc cA cc wcel cA cA cc wcel id 2timesd oveq2d $.
adva152e49 $p |- ( A e. CC -> ( ( 2 x. A ) + ( A + A ) ) = ( ( A + A ) + ( A + A ) ) ) $= cA cc wcel c2 cA cmul co cA cA caddc co cA cA caddc co caddc cA cc wcel cA cA cc wcel id 2timesd oveq1d $.
adva152e50 $p |- ( A e. CC -> ( ( A + A ) + ( A + A ) ) = ( ( 2 x. A ) + ( A + A ) ) ) $= cA cc wcel cA cA caddc co c2 cA cmul co cA cA caddc co caddc cA cc wcel c2 cA cmul co cA cA caddc co cA cc wcel cA cA cc wcel id 2timesd eqcomd oveq1d $.
adva152e51 $p |- ( A e. CC -> ( ( 2 x. A ) + ( A + A ) ) = ( ( A + A ) + ( A + A ) ) ) $= cA cc wcel c2 cA cmul co cA cA caddc co cA cA caddc co caddc cA cc wcel cA cA cc wcel id 2timesd oveq1d $.
adva152e52 $p |- ( A e. CC -> ( ( A + A ) + ( A + A ) ) = ( ( A + A ) + ( 2 x. A ) ) ) $= cA cc wcel cA cA caddc co c2 cA cmul co cA cA caddc co caddc cA cc wcel c2 cA cmul co cA cA caddc co cA cc wcel cA cA cc wcel id 2timesd eqcomd oveq2d $.
adva152e53 $p |- ( A e. CC -> ( ( A + A ) + ( 2 x. A ) ) = ( ( A + A ) + ( A + A ) ) ) $= cA cc wcel c2 cA cmul co cA cA caddc co cA cA caddc co caddc cA cc wcel cA cA cc wcel id 2timesd oveq2d $.
adva152e54 $p |- ( A e. CC -> ( ( A + A ) + ( A + A ) ) = ( 2 x. ( A + A ) ) ) $= cA cc wcel c2 cA cA caddc co cmul co cA cA caddc co cA cA caddc co caddc co cA cc wcel cA cA caddc co cA cc wcel cA cA cA cc wcel id cA cc wcel id addcld 2timesd eqcomd $.
adva152e55 $p |- ( A e. CC -> ( 2 x. ( A + A ) ) = ( ( A + A ) + ( A + A ) ) ) $= cA cc wcel cA cA caddc co cA cc wcel cA cA cA cc wcel id cA cc wcel id addcld 2timesd $.
adva152e56 $p |- ( A e. CC -> ( ( A + A ) + ( A + A ) ) = ( ( 2 x. A ) + ( A + A ) ) ) $= cA cc wcel cA cA caddc co c2 cA cmul co cA cA caddc co caddc cA cc wcel c2 cA cmul co cA cA caddc co cA cc wcel cA cA cc wcel id 2timesd eqcomd oveq1d $.
adva152e57 $p |- ( A e. CC -> ( ( 2 x. A ) + ( A + A ) ) = ( ( 2 x. A ) + ( 2 x. A ) ) ) $= cA cc wcel cA cA caddc co c2 cA cmul co c2 cA cmul co caddc cA cc wcel c2 cA cmul co cA cA caddc co cA cc wcel cA cA cc wcel id 2timesd eqcomd oveq2d $.
adva152e58 $p |- ( A e. CC -> ( ( 2 x. A ) + ( 2 x. A ) ) = ( 2 x. ( 2 x. A ) ) ) $= cA cc wcel c2 c2 cA cmul co cmul co c2 cA cmul co c2 cA cmul co caddc co cA cc wcel c2 cA cmul co cA cc wcel c2 cA cA cc wcel 2cnd cA cc wcel id mulcld 2timesd eqcomd $.
adva152e59 $p |- ( A e. CC -> ( ( A + A ) + ( A + A ) ) = ( ( 2 x. A ) + ( A + A ) ) ) $= cA cc wcel cA cA caddc co c2 cA cmul co cA cA caddc co caddc cA cc wcel c2 cA cmul co cA cA caddc co cA cc wcel cA cA cc wcel id 2timesd eqcomd oveq1d $.
adva152e60 $p |- ( A e. CC -> ( ( 2 x. A ) + ( A + A ) ) = ( ( 2 x. A ) + ( 2 x. A ) ) ) $= cA cc wcel cA cA caddc co c2 cA cmul co c2 cA cmul co caddc cA cc wcel c2 cA cmul co cA cA caddc co cA cc wcel cA cA cc wcel id 2timesd eqcomd oveq2d $.
adva152e61 $p |- ( A e. CC -> ( ( 2 x. A ) + ( 2 x. A ) ) = ( 2 x. ( 2 x. A ) ) ) $= cA cc wcel c2 c2 cA cmul co cmul co c2 cA cmul co c2 cA cmul co caddc co cA cc wcel c2 cA cmul co cA cc wcel c2 cA cA cc wcel 2cnd cA cc wcel id mulcld 2timesd eqcomd $.
adva152e62 $p |- ( A e. CC -> ( ( A + A ) + ( A + A ) ) = ( 2 x. ( A + A ) ) ) $= cA cc wcel c2 cA cA caddc co cmul co cA cA caddc co cA cA caddc co caddc co cA cc wcel cA cA caddc co cA cc wcel cA cA cA cc wcel id cA cc wcel id addcld 2timesd eqcomd $.
adva152e63 $p |- ( A e. CC -> ( 2 x. ( A + A ) ) = ( 2 x. ( 2 x. A ) ) ) $= cA cc wcel cA cA caddc co c2 cA cmul co c2 cmul cA cc wcel c2 cA cmul co cA cA caddc co cA cc wcel cA cA cc wcel id 2timesd eqcomd oveq2d $.
adva152e64 $p |- ( A e. CC -> ( ( A + A ) + ( A + A ) ) = ( ( 2 x. A ) + ( A + A ) ) ) $= cA cc wcel cA cA caddc co c2 cA cmul co cA cA caddc co caddc cA cc wcel c2 cA cmul co cA cA caddc co cA cc wcel cA cA cc wcel id 2timesd eqcomd oveq1d $.
adva152e65 $p |- ( A e. CC -> ( ( 2 x. A ) + ( A + A ) ) = ( ( A + A ) + ( A + A ) ) ) $= cA cc wcel c2 cA cmul co cA cA caddc co cA cA caddc co caddc cA cc wcel cA cA cc wcel id 2timesd oveq1d $.
adva152e66 $p |- ( A e. CC -> ( ( A + A ) + ( A + A ) ) = ( 2 x. ( A + A ) ) ) $= cA cc wcel c2 cA cA caddc co cmul co cA cA caddc co cA cA caddc co caddc co cA cc wcel cA cA caddc co cA cc wcel cA cA cA cc wcel id cA cc wcel id addcld 2timesd eqcomd $.
adva152e67 $p |- ( A e. CC -> ( 2 x. ( A + A ) ) = ( ( A + A ) + ( A + A ) ) ) $= cA cc wcel cA cA caddc co cA cc wcel cA cA cA cc wcel id cA cc wcel id addcld 2timesd $.
adva152e68 $p |- ( A e. CC -> ( ( A + A ) + ( A + A ) ) = ( 2 x. ( A + A ) ) ) $= cA cc wcel c2 cA cA caddc co cmul co cA cA caddc co cA cA caddc co caddc co cA cc wcel cA cA caddc co cA cc wcel cA cA cA cc wcel id cA cc wcel id addcld 2timesd eqcomd $.
adva152e69 $p |- ( A e. CC -> ( 2 x. ( A + A ) ) = ( 2 x. ( 2 x. A ) ) ) $= cA cc wcel cA cA caddc co c2 cA cmul co c2 cmul cA cc wcel c2 cA cmul co cA cA caddc co cA cc wcel cA cA cc wcel id 2timesd eqcomd oveq2d $.
adva152e70 $p |- ( A e. CC -> ( ( A + A ) + ( A + A ) ) = ( ( 2 x. A ) + ( A + A ) ) ) $= cA cc wcel cA cA caddc co c2 cA cmul co cA cA caddc co caddc cA cc wcel c2 cA cmul co cA cA caddc co cA cc wcel cA cA cc wcel id 2timesd eqcomd oveq1d $.
adva152e71 $p |- ( A e. CC -> ( ( 2 x. A ) + ( A + A ) ) = ( ( 2 x. A ) + ( 2 x. A ) ) ) $= cA cc wcel cA cA caddc co c2 cA cmul co c2 cA cmul co caddc cA cc wcel c2 cA cmul co cA cA caddc co cA cc wcel cA cA cc wcel id 2timesd eqcomd oveq2d $.
adva152e72 $p |- ( A e. CC -> ( ( 2 x. A ) + ( 2 x. A ) ) = ( 2 x. ( 2 x. A ) ) ) $= cA cc wcel c2 c2 cA cmul co cmul co c2 cA cmul co c2 cA cmul co caddc co cA cc wcel c2 cA cmul co cA cc wcel c2 cA cA cc wcel 2cnd cA cc wcel id mulcld 2timesd eqcomd $.
adva152e73 $p |- ( A e. CC -> ( ( A + A ) + ( A + A ) ) = ( 2 x. ( A + A ) ) ) $= cA cc wcel c2 cA cA caddc co cmul co cA cA caddc co cA cA caddc co caddc co cA cc wcel cA cA caddc co cA cc wcel cA cA cA cc wcel id cA cc wcel id addcld 2timesd eqcomd $.
adva152e74 $p |- ( A e. CC -> ( 2 x. ( A + A ) ) = ( 2 x. ( 2 x. A ) ) ) $= cA cc wcel cA cA caddc co c2 cA cmul co c2 cmul cA cc wcel c2 cA cmul co cA cA caddc co cA cc wcel cA cA cc wcel id 2timesd eqcomd oveq2d $.
